---
- name: Init VM on Hypervisor
  hosts: hypervisors
  gather_facts: yes
  pre_tasks:

    - name: Loading vm definitions
      include_vars:
        file: vms_config.yaml
        name: my_vms_config
      # allow to override using -e
      when: not( my_vms_config is defined )
      ignore_errors: yes

  roles:

    - role: parse_vms_definitions
      vars:
        config: "{{ my_vms_config }}"

  tasks:
    # add VMs definitions to the ansible inventory
    - name: init VM connection
      loop: "{{ virtual_machines }}"

      include_role:
        name: init_vm_connection

      loop_control:
        loop_var: vm
      vars:
        vm: "{{ vm }}"

- name: VM provisioning on Hypervisor host
  hosts: vms
  gather_facts: no
  serial: 1
  tasks:

    - block:

      - name: Gather min facts if definitions use them.
        setup:
          gather_subset:
            - '!all'

      - name: "Start KVM Provision role for '{{ vm.metadata.name }}'."
        include_role:
          name: kvm_provision

      delegate_to: "{{ kvm_host }}"
      tags:
        - kvm_provision
      when: false  # uncomment to skip vm provisioning


    - block:

      - name: "Start VM test cycle for '{{ vm.metadata.name }}'."
        include_role: 
          name: guest_provision
        vars:
          allowed_phases:
            # - startup
            - restore init
            # - create init
            # - restore clean
            # - create clean
            # - dependencies
            # - init
            - main
            # - terminate
            # - shutdown

      tags:
        - guest_provision
