---

- block:

    - name: Parse pytest.ini to determine test groups.
      get_farm_test_groups:
      register: farm_test_groups

    - name: Get timestamp from the local system.
      shell: "date +%Y%m%d_%H%M%S"
      register: tstamp

  delegate_to: localhost

- block:

    # Launch all test groups, one by one

    - name: launch multiple test groups.
      include_tasks: launch_tests.yml
      vars:
        output_folder: "{{ tests_output_folder }}/{{ tstamp.stdout }}"
        tests_filter: "-m {{ item }}"
        output_xml: "out_{{ item }}.xml"
        output_html: "out_{{ item }}.html"
        # don't restore init after the last group!
        restore_init: "{{ group_index < farm_test_groups.groups|length - 1 }}"
      loop: "{{ farm_test_groups.groups }}"
      loop_control:
          index_var: group_index

  when: farm_test_groups.groups|length > 0

# else 
- block:

    - name: Launch all collected tests.
      include_tasks: launch_tests.yml
      vars:
        output_folder: "{{ tests_output_folder }}/{{ tstamp.stdout }}"
        tests_filter: ""  # should be empty when selecting all tests!
        output_xml: "out_all.xml"
        output_html: "out_all.html"
        restore_init: false  # no need to restore the init snapshot

  when: farm_test_groups.groups|length == 0