---

# Install vdens and vde_plug with the v2 script
# NOTE: this is too broad, it should only install what's really needed
- block:

    - name: Make sure the clock is in sync.
      shell: /usr/sbin/hwclock --hctosys 

    - name: Make sure the system is up to date.
      apt:
        update_cache: yes
        cache_valid_time: 3600
        state: latest
        upgrade: yes

    # TODO refactor this kludge
    - name: Launch the virtualsquare install script.
      command: /bin/bash -c "cd /root && export PATH=$PATH:/usr/sbin && DEBIAN_FRONTEND=noninteractive ./get_v2all > /tmp/out 2>&1"

    - name: Reboot the vm.
      ansible.builtin.reboot:
 
  become: yes

# prepare the test suite on the vm guest
- include_role:
    name: setup_test_suite

# any additional test dependencies should be installed here
